create table product
(
    id        bigint generated by default as identity,
    price     integer      not null,
    name      varchar(15)  not null,
    image_url varchar(255) not null,
    primary key (id)
);

create table users
(
    id       bigint generated by default as identity,
    email    varchar(255) not null unique,
    password varchar(255) not null,
    primary key (id)
);

create table wish
(
    id         bigint generated by default as identity,
    user_id  bigint not null,
    product_id bigint not null,
    primary key (id)
);

alter table if exists wish
    add constraint fk_wish_user_id_ref_user_id
    foreign key (user_id)
    references users;

alter table if exists wish
    add constraint fk_wish_product_id_ref_product_id
    foreign key (product_id)
    references product;